# Generated by Django 5.1.1 on 2024-11-26 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai_segment_mark",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="ai_segment_mark",
            name="user",
        ),
        migrations.CreateModel(
            name="User_segment_mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.CharField(max_length=255)),
                ("comment", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.segment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
