# Generated by Django 5.1.1 on 2024-12-08 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_ai_segment_mark_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_segment_mark',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ai_segment_mark',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_segment_mark',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_segment_mark',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
