# Generated by Django 5.1.1 on 2024-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_ai_segment_mark_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=255)),
                ('mag', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='end_point',
            new_name='lan',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='start_point',
            new_name='mag',
        ),
    ]
